const foodShelfLife = {
  卵: { days: 14 },
  たまご: { days: 14 },

  牛乳: { days: 7 },
  メグミルク: { days: 7 },

  パン: { days: 5 },
  食パン: { days: 5 },
  ロールパン: { days: 5 },

  ピーマン: { days: 7 },
  きゅうり: { days: 7 },
  キュウリ: { days: 7 },
  きゅーり: { days: 7 },
  トマト: { days: 7 },
  ミニトマト: { days: 7 },
  玉ねぎ: { days: 14 },
  たまねぎ: { days: 14 },
  にんじん: { days: 14 },
  じゃがいも: { days: 14 },
  キャベツ: { days: 10 },
  レタス: { days: 5 },
  白菜: { days: 7 },
  もやし: { days: 3 },
  長ねぎ: { days: 7 },
  ねぎ: { days: 5 },
  大根: { days: 10 },
  小松菜: { days: 4 },
  ほうれん草: { days: 4 },
  ブロッコリー: { days: 5 },
  しめじ: { days: 5 },
  えのき: { days: 5 },
  まいたけ: { days: 5 },
  エリンギ: { days: 5 },

  豆腐: { days: 3 },
  納豆: { days: 7 },
  ヨーグルト: { days: 7 },
  チーズ: { days: 14 },
  バター: { days: 30 },

  豚肉: { days: 3 },
  豚こま: { days: 3 },
  豚バラ: { days: 3 },
  鶏肉: { days: 3 },
  鶏むね肉: { days: 3 },
  鶏もも肉: { days: 3 },
  ひき肉: { days: 2 },
  合いびき肉: { days: 2 },
  牛肉: { days: 3 },

  ウインナー: { days: 10 },
  ソーセージ: { days: 10 },
  ハム: { days: 7 },
  ベーコン: { days: 7 },

  鮭: { days: 2 },
  さけ: { days: 2 },
  鯖: { days: 2 },
  さば: { days: 2 },
  刺身: { days: 1 },

  バナナ: { days: 5 },
  りんご: { days: 14 },
  みかん: { days: 7 },
  いちご: { days: 3 },

  牛乳プリン: { days: 5 },
  プリン: { days: 5 },
  ゼリー: { days: 7 },

  冷凍うどん: { days: 30 },
  うどん: { days: 5 },
  そば: { days: 5 },
  焼きそば: { days: 5 },
  パスタ: { days: 30 },

  ごはん: { days: 1 },
  おにぎり: { days: 1 },
  惣菜: { days: 1 },
  弁当: { days: 1 },

  マヨネーズ: { days: 30 },
  ケチャップ: { days: 30 },
  味噌: { days: 90 },
  納豆巻き: { days: 1 },
};

export default foodShelfLife;